README.md

Updated links in readme to heroku url

Updated with heroku url

---

composer.json
composer.lock
src/index.php
tests/OptionsTest.php
tests/RendererTest.php

Changed composer to autoload classes as needed in order to simplify the import statements.

Autoload models and views

---

src/models/RendererModel.php
src/templates/main.php
tests/svg/test_normal.svg

Escaping special characters to prevent certain SVG links (when viewed as a page in the browser) from being able to execute scripts in the lines parameter.
Fixes #7

Escape characters passed to lines to prevent code injection

---

README.md

Replaced demo screenshot with animated gif
Fixes # 
#14 
Update

Replace Demo Screenshot With GIF

---

README.md

Consistent case and changed PHP version

---

README.md

Add @krishdevdb To The Example Usage Section
References #21

Add krishdevdb to the example usage section

---

src/demo/css/style.css
src/demo/index.php

Updated buttons to use https://buttons.github.io/ since they look nicer and are aligned better
Before:
After:

Update site buttons with buttons.github.io

---

src/demo/js/toggle-dark.js

Switch to dark mode if it is the user's system/browser preference
Fixes #36

Set mode that user prefers

---

README.md

Added deploy to heroku instructions to readme

Added Deploy to Heroku instructions

---

README.md

Added user count badge to readme

---

README.md

Added Tarun-Kamboj to README.md

---

README.md

Added a new example profule to `example usage`

added my profile to `example usage`

---

.github/workflows/release.yml
.github/workflows/stale.yml

release.yml - automated releases
stale.yml - mark and close issues with no activity

Release and Stale workflows

---

README.md

Using a Google font so text no longer appears cut off with different monospace fonts.
Fixes #29

Added font parameter and increased width for readme example

---

README.md

Added my profile, [angelofallars](https://github.com/angelofallars) to README.md
References #21

Add angelofallars to README.md

---

README.md

Add sudoshivam to README.md

---

README.md

Hey I'm added my profile in readme
profile link added in readme

add profile in readme

---

src/demo/index.php

remove error message displayed on browser

Fix darkmode toggle

---

README.md

Hey Jonah! Thanks for this awesome tool!! I'm adding this to my Readme :p

Add: PROxZIMA to ReadMe

---

README.md

add VydrOz to README

---

README.md

Added Carol42 to README

---

README.md

Example usage profiles
Fixes #

docs(readme): Added Thakur Ballary to README

---

README.md
src/demo/index.php
src/demo/js/script.js
src/models/RendererModel.php
src/templates/main.php
src/views/RendererView.php
tests/OptionsTest.php
tests/svg/test_fonts.svg
tests/svg/test_multiline.svg
tests/svg/test_normal.svg
tests/svg/test_normal_vertical_alignment.svg

Allows setting the background color with `background=<color>`
Resolves #2

feat: Adds background color parameter

---

src/demo/css/style.css
src/demo/index.php

fix(demo): Rename labels and add font tooltip

---

README.md

docs(readme): Add Huynh Duong to README

---

README.md

docs(readme): Add example profile to README

---

README.md

Added myself.

---

README.md

docs(readme): Added manthan ank's profile

---

README.md

Added Ronny Coste to Readme

---

README.md

Added Vishal-Beep to readme in example usage!

docs(readme): Added Vishal-Beep to examples

---

README.md

Added raihankhan profile link in readme

docs(readme): Add raihankhan to examples

---

docs/faq.md

docs: Add more questions and answers to the FAQ

---

.github/pull_request_template.md

Removes some areas of the pull request template to make contributing easier

chore: Simplified the Pull Request template

---

README.md

Added notauserx to the readme example usage section.

Added notauserx to readme example usage

---

README.md

docs(readme): Fix broken link in examples

---

README.md

added wiz64 to readme (example users)

docs(readme): Added wiz64 to examples

---

README.md

Update duration and pause in the header SVG

docs(readme): Update duration and pause in the header SVG

---

README.md

The current demo gif is a bit outdated and is missing some of the new features.
This is a new recording showing the demo site's features.
[![Demo Site](https://user-images.githubusercontent.com/20955511/183703055-42ec8754-d84c-414f-8132-a02974224aa1.gif "Demo Site")](https://readme-typing-svg.herokuapp.com/demo/)

docs(readme): Update gif with the new demo site

---

README.md

docs(readme): Added D3vil0per to examples

---

README.md

docs(readme): Added EliusHHimel to examples

---

README.md

Add myself (jcs090218) to example.
Thanks for this amazing tool! ❤️ I have also added to my [profile](https://www.jcs-profile.com/) and [gitlab](https://gitlab.com/jcs090218) page! 😁

docs(README.md): Add jcs090218 to examples

---

README.md

Added another awesome username, who uses the fantastic typing-SVG feature😄!!

docs(readme): Added Rishabh2804 to examples

---

README.md

Add another user of this awesome tool to README

Add UlisesAlexanderAM to README

---

README.md

I just came across this wonderful repository. Thank you for your hard work. I'm working on something like this typing animation right now, and your work inspired me a lot!
If you're interested, take a look a while
https://spookyjelly.github.io/react-chicago/
Once again, Thanks a lot!

docs(readme): Add SpookyJelly to Readme

---

README.md

docs(readme): Added yousafesaeed to examples

---

README.md

docs(readme): Added CFCIFE to examples

---

README.md

docs(readme): Add majidtdeni666 to examples

---

README.md

docs(readme): Fix image size in examples

---

README.md

Thank you for this repo, I really love your work!

docs(readme): Add GalexY727 to examples

---

README.md

docs(readme): Added HectorSaldes to examples

---

README.md

Added example to README.md

---

README.md

docs(readme): Added cracker911181 to examples

---

README.md

docs: Added example to README

---

.github/workflows/phpunit-ci-coverage.yml

chore(deps): Update ci workflow deps

---

README.md

docs(readme): Remove examples without typing SVGs

---

README.md

docs(readme): Added ManoBharathi93 to examples

---

README.md

Adding kaisunoo to the profiles who uses typing svg.
- Updated documentation (updated the readme, templates, or other repo files)

docs(readme): Added kaisunoo to examples

---

README.md

Added [jeremiahseun](https://www.github.com/jeremiahseun) to README 🎉

docs(readme): Added jeremiahseun to examples

---

README.md

Added "creativepuru" in 🚀 Example usage of README
Link Added : [![Purushottam Anand](https://github.com/creativepuru.png?size=100)](https://github.com/creativepuru "Purushottam Anand 🇮🇳 on GitHub ☕")

docs(readme): Added creativepuru to examples

---

README.md

docs(readme): Added gchism94 to examples

---

README.md
src/demo/js/script.js
src/models/RendererModel.php
tests/OptionsTest.php
tests/RendererTest.php

feat: Support for semicolons and custom separator

---

src/demo/js/script.js

fix(demo): Support lines ending with and starting with semicolon on demo

---

README.md

docs(readme): Added K1rsN7 to README

---

README.md

docs(readme): Added codesbyahsen to examples

---

.github/workflows/prettier.yml

ci: Roll back prettier version to work with prettier-php

---

README.md

docs(readme): Add Shiro-cha to examples

---

README.md

Added Jini by Rentalz.com to readme examples

docs(readme): Add Jini by Rentalz.com to examples

---

src/demo/index.php

Reverts DenverCoder1/readme-typing-svg#231

revert: fix(demo): update GitHub stars link

---

.github/workflows/phpunit-ci-coverage.yml

ci: Update composer action to latest commit

---

README.md

I have added my Profile in the readme . Please accept it as soon as possible .

Added Srijan-Baniyal to Readme.md

---

.github/workflows/prettier.yml

ci: Lock specific prettier plugin-php version

---

README.md

I realized I added my information earlier

Revert "docs(readme): Added CFCIFE to examples"

---

.github/workflows/prettier.yml

ci(prettier): Include git diff in Prettier workflow output

---

README.md

Added zidk to readme

---

README.md

docs(readme): Added DeveshYadav13 to examples

---

src/demo/index.php
src/models/RendererModel.php
tests/OptionsTest.php
tests/RendererTest.php

feat: Add option to put lines in random order

---

README.md

Add HauseMaster to example usage.

docs(readme): Add HauseMaster to Examples

---

README.md

docs(readme): Replace gravatar image that could not be resized through the query string

---

README.md

new user added: elvisisvan
~~user removed: ManoBharathi93~~
~~reason: errored profile image wrecks havoc to the uniformity of profile table~~

docs(readme): Added Elvis Van to examples

---

README.md

docs(readme): Added example to README

---

README.md

docs(readme): Added Elio-Aliaj to examples

---

README.md

docs(readme): Added presentformyfriends to examples

---

README.md

This change will add [my](https://github.com/LakshmanKishore) GitHub Account in the readme.

docs(readme): Add LakshmanKishore to examples

---

README.md

Added my profile to examples list on README.

Added mateusadada to README

---

README.md

I added myself to the people who are using this repo on their github profile page.

Added YousifAbozid to README.md

---

README.md

Hello 👋,
I wanted to inform you that I have recently changed my GitHub username from `LinThit27` to `LinThitHtwe`. As a result, I need to update the old URL associated with my username in this repository.
Thank you for your attention to this matter.
- [✔️ ] Updated documentation (updated the readme, templates, or other repo files)

docs(readme): Update LinThit27 to LinThitHtwe

---

README.md

docs(readme): Added hheinsoee to examples

---

README.md

docs(readme): Added lucmsilva to examples

---

README.md

docs(readme): Added ashertenenbaum to examples

---

README.md

docs(readme): Added 0dxplt to examples

---

README.md

Added HerobrineTV to the Readme

Added HerobrineTV to the Readme

---

README.md

docs(readme): add Borketh to examples

---

app.json

chore: Fix formation size

---

composer.lock
src/demo/js/script.js

fix: Add default value for random

---

src/demo/js/script.js

docs: Added documentation to JS

---

src/demo/index.php
src/demo/js/script.js

feat(demo): Open permalink button and restore params from URL

---

README.md

docs(readme): Added CallMeProteus to examples

---

README.md

Add suzukimain to Example usage in Readme.

docs(readme): Added suzukimain to examples

---

README.md

Added caesar013 README.md

---

README.md

docs(readme): Added amir78729 to examples

---

README.md

Add Yogi Hariyani to README file

---

README.md

Added Eligijus Ciza to README.md

Added Eligijus Ciza to README.md

---

README.md

Added Ashish-CodeJourney to README.md

Added Ashish-CodeJourney to README.md

---

README.md

Github account does not exist / deleted
Removed SuSheng13T because that account does not exists / deleted

Removed SuSheng13T

---

README.md

docs(readme): Added AustinMusuya to examples

---

README.md

Added SarthakKrishak in README.md

---

README.md

docs(readme): Added Snoopy1866 to examples

---

README.md

docs(readme): fix profile image

---

README.md

docs(readme): Add Rohit to examples

---

README.md

Added saadhusayn to README

---

README.md

Added EchoSingh to README

---

README.md

-  Updated documentation (updated the readme, templates, or other repo files)

docs: Added Muhammad-Noraeii to examples

---

README.md

no comment needed I guess...
Nice thing to add to your readme!
I'd recommend it!

Added wfxey to Readme

---

README.md

Added AhmedNassar7 to README
