- README.md
First of all: Thank you so much for such an amazing project. Just the other day when I was working on my github profile I wanted exactly this. Sadly that day I didn't come across this amazing project and so went through the hassle of recording a typing animation -> converting it to a gif -> uploading it to my repo -> and then finally linking it in my readme. This project makes it so much easier.
**This PR adds my profile to the example list, now that I switched to use this project instead of my manually created gif. You can see two occurrences of the typing animation on my profile.**
Lastly I want to ask if you (@DenverCoder1)  already have plans to work on this margin-bottom that is present within the generated svg. The generated text is not vertically aligned and even when reducing the …
> Add profile to example list

- src/models/RendererModel.php
- tests/RendererTest.php
This PR trims trailing ";" separators from the `lines` query param before separating them into a list.
This prevents an empty line to be animated.
Fixes #25
> Fix empty line when "lines" have a trailing ";" separator

- README.md
- src/demo/css/style.css
- src/demo/index.php
- src/demo/js/script.js
- src/models/RendererModel.php
- src/templates/main.php
- src/views/RendererView.php
- tests/OptionsTest.php
- tests/RendererTest.php
- tests/svg/test_fonts.svg
- tests/svg/test_missing_lines.svg
- tests/svg/test_multiline.svg
- tests/svg/test_normal.svg
- tests/svg/test_normal_vertical_alignment.svg
Fixes #27
This PR adds the feature to control the vertical alignment over a new query param call `vCenter`. The vertical alignment was previously coupled with the horizontal alignment and controlled over `center`. With this PR we now separate the control over them.
> Control vertical text alignment

- src/demo/index.php
> Change color picker to use hex instead of hexa

- README.md
The examples list is getting pretty long and takes up a lot of space in the Readme.
To solve this, I have decided to switch all links to icons instead of list items.
> docs: Change examples list to profile pictures

- src/templates/main.php
- tests/svg/test_fonts.svg
- tests/svg/test_multiline.svg
- tests/svg/test_normal.svg
- tests/svg/test_normal_vertical_alignment.svg
Safari does not show animations when keyTimes contain spaces.
This removes spaces from keyTimes for compatibility with Safari.
Fixes #71
> fix: remove spaces from keyTimes for Safari

- README.md
Adds a step to the Heroku instructions for configuring the database to use custom fonts / Google fonts
> docs(readme): Add step for configuring the database

- docs/faq.md
> docs: Added Docs for FAQs

- src/demo/css/style.css
- src/demo/index.php
- src/demo/js/script.js
> feat(demo): add html output to demo site

- README.md
- src/demo/index.php
- src/demo/js/script.js
- src/models/RendererModel.php
- src/templates/main.php
- src/views/RendererView.php
- tests/OptionsTest.php
- tests/RendererTest.php
- tests/svg/test_fonts.svg
- tests/svg/test_multiline.svg
- tests/svg/test_normal.svg
- tests/svg/test_normal_vertical_alignment.svg
- tests/svg/test_pause.svg
- tests/svg/test_pause_multiline.svg
Adds a pause parameter to create a delay between lines of text.
Fixes #118
> feat: Add pause duration parameter

- .github/workflows/release.yml
Change release to be on dispatch instead of push. Some changes are pretty small and don't really require their own release. This allows more easily combining commits in a single release.
> ci: Change release to be on dispatch instead of push

- src/demo/index.php
Modified some preview values on the **Demo Site**.
**NOTE: The default values for typing SVGs have not changed, this change only affects the settings on the demo site.**
- Font changed from `monospace` to `Fira Code`
- `monospace` has some issues in that it displays differently depending on the user's browser and can get cut off if the user has a wide monospace font installed. `Fira Code` is a specific font from Google fonts so should display the same width for all users.
- Pause changed from `500` to `1000`, it seems to be a better amount for a noticeable pause.
- Width changed from `400` to `435`. This width seems to work well when using Fira Code on the example pangram lines.
> feat(demo): Updated demo site default values

- src/demo/css/style.css
- src/demo/index.php
Adds the FAQ link to the demo site
> feat(demo): add the FAQ link to the demo site

- src/demo/index.php
- src/templates/error.php
- src/templates/main.php
Replace `<?php echo` with `<?=` shorthand for readability
> style: replace `<?php echo` with `<?=` shorthand

- README.md
- docs/faq.md
It is still hosted on Heroku, just added a new custom domain to make it easier to move the hosting in the future if necessary
> docs: Update links to demolab custom domain

- README.md
* Readme quick start improvements
* Removed contributing info from readme and instead included a link to the contributing.md file
> docs(readme): Update quick start and create link to contributing.md

- README.md
I used to be vantro, name changed.
> docs(readme): Added example to readme

- src/demo/index.php
- src/demo/js/script.js
- src/models/GoogleFontConverter.php
- src/models/RendererModel.php
**Feature**
Added option to specify font-weight, as available on Google Fonts.
It has been tested locally, manually and by running ```composer test```
I believe it's not necessary to create additional tests for this feature
> feature: Added font-weight support

- src/demo/index.php
- src/demo/js/script.js
- added button code in index.php
- added reset code in script.js
- Have not been tested
> feat(demo): Added a Reset button

- README.md
- src/demo/index.php
- src/demo/js/script.js
- src/models/RendererModel.php
- src/templates/main.php
- src/views/RendererView.php
- tests/OptionsTest.php
- tests/RendererTest.php
- tests/svg/test_normal.svg
Add repeat option defaulting to true.
`repeat=true` - current behavior, loop to beginning of animation when complete
`repeat=false` - leave the last line frozen in place when it is completed
Fixes #180
> feat: Added repeat option to disable loop

- README.md
Adding ProfCyberNaught to the example usage section as I am actively using this feature on my profile page on GitHub.
I have been using this feature on my profile for a while now (at the very top) and notice, you were able to submit a pull request containing your own profile image and link to profile on GitHub. I think this is a great idea to demonstrate the usage scenario on active and engaged profiles.
I have added my own profile image, along with a link to my GitHub profile page, and the link title text: ProfCyberNaught on GitHub.
> docs(readme): Added ProfCyberNaught to examples

- README.md
> docs(readme): Added Meyer Pidiache to examples

- src/demo/js/script.js
> fix(demo): Limit range of separator characters used in demo

- src/demo/index.php
- Update GitHub stars link.
I don't think this applies here.
> fix(demo): update GitHub stars link

- src/demo/js/script.js
Improved the clipboard code by replacing the deprecated **document.execCommand** with the modern Clipboard API (**navigator.clipboard.writeText**).
> refactor: Improved clipboard copying code

- README.md
> Added my profile to README

- src/demo/index.php
This change adds a mechanism (e.g., a `translate="no"` attribute) on key text elements to prevent Microsoft Edge from automatically translating specific words. This fix ensures that the intended text remains unchanged when using Edge's webpage translation feature.
Additionally, the fix was verified manually by running the demo page in Microsoft Edge with translation enabled to ensure that key text remains unchanged.
Closes #336
> fix: disable translation on key elements
